Plugin Name: gcSequencer
Plugin Version: 5.6.1
Server Main: com.growcontrol.plugins.gcsequencer.server.gcSequencer.class
Client Main: com.growcontrol.plugins.gcsequencer.client.gcSequencer.class
Author: lorenzop
Website: http://growcontrol.com/
Depend: []
SoftDepend: []