Plugin Name: gcSequencer
App Version: 3.6.2
Server Main: com.growcontrol.plugins.gcsequencer.server.gcSequencer.class
Client Main: com.growcontrol.plugins.gcsequencer.client.gcSequencer.class
Author: lorenzop
Website: http://growcontrol.com/
Depend: []
SoftDepend: []
